import asyncio
import asyncpg
import logging


async def main():
    connection = await asyncpg.connect(host='127.0.0.1',
                                       port=5432,
                                       user='postgres',
                                       database='products',
                                       password='password')
    async with connection.transaction():
        await connection.execute("INSERT INTO brand VALUES(DEFAULT, 'my_new_brand')")

        try:
            async with connection.transaction():
                await connection.execute("INSERT INTO product_color VALUES(1, 'black')")
        except Exception as ex:
            logging.warning('Ignoring error inserting product color', exc_info=ex)

    # print(await connection.fetch('SELECT * FROM brand WHERE brand_name = $1', 'my_new_brand'))
    # print(await connection.fetch('SELECT * FROM brand WHERE id = 1'))
    await connection.close()


asyncio.run(main())